# -*- coding: utf-8 -*-
"""Material informatics - Concrete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tlzkibvhxhg35aa9856Dcv_Japc0tWpF
"""

#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_percentage_error
from scipy.optimize import curve_fit

#import file
file_path = '/content/drive/MyDrive/Colab Notebooks/Concrete_Data.xls'
df = pd.read_excel(file_path)
df.columns = ['Cement', 'Slag', 'FlyAsh', 'Water', 'Superplasticizer',
              'CoarseAgg', 'FineAgg', 'Age', 'Strength']

#keyparameter to optimise
X = ['Cement', 'Slag', 'FlyAsh', 'Water', 'Superplasticizer', 'CoarseAgg', 'FineAgg', 'Age']
y = ['Strength']

#Physical model for the strength of concrete
#Generalised Abram's Law combined with time function

def physical_strength_formula(X, K_agg, K_time, k_slag, k_flyash):

    cement, slag, flyash, water, age = X

    effective_binder = cement + (k_slag * slag) + (k_flyash * flyash)
    bw_ratio = effective_binder / water


    potential_strength = K_agg * (bw_ratio)


    time_factor = age / (K_time + age)
    return potential_strength * time_factor

#Physical model executation

X_physical = (df['Cement'].values, df['Slag'].values, df['FlyAsh'].values, df['Water'].values, df['Age'].values)
y_physical = df['Strength'].values
# K_agg=30, K_time=5 days, k_slag=0.9, k_flyash=0.3
p0 = [30.0, 5.0, 0.9, 0.3]

popt, pcov = curve_fit(physical_strength_formula, X_physical, y_physical, p0=p0, bounds=([0,0,0,0], [np.inf, np.inf, np.inf, np.inf]))

K_agg_fit, K_time_fit, k_slag_fit, k_flyash_fit = popt


# Calculate Predictions using the fitted formula
y_pred_phys = physical_strength_formula(X_physical, *popt)
r2_phys = r2_score(y_physical, y_pred_phys)
print(f"Physical Formula R2 Score: {r2_phys:.4f}")
print("Fitted Physical Constants:")
print(f"  Aggregates Quality (K_agg): {K_agg_fit:.2f}")
print(f"  Time Half-Life (K_time): {K_time_fit:.2f} days")
print(f"  Slag Efficiency: {k_slag_fit:.2f}")
print(f"  Fly Ash Efficiency: {k_flyash_fit:.2f}")

#Machine learning parameters

X = ['Cement', 'Slag', 'FlyAsh', 'Water', 'Superplasticizer', 'CoarseAgg', 'FineAgg', 'Age']
y = ['Strength']

X_train, X_test, y_train, y_test = train_test_split(df[X], df[y], random_state=42, test_size=0.2)

model = RandomForestRegressor (n_estimators=100, random_state=42)

model.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)



r2 = r2_score(y_test, y_pred)
mean_absolute_error = mean_absolute_percentage_error(y_test, y_pred)
print(f"R-squared score: {r2:.2f}")
print(f"Mean Absolute Percentage Error: {mean_absolute_error:.2f}%")

# Plot Comparison
plt.figure(figsize=(10, 6))
plt.scatter(y_physical, y_pred_phys, alpha=0.5, color='green', label='Physical Formula')
plt.scatter(y_test, y_pred, alpha=0.1, color='blue', label='Random Forest (Ref)')

# Perfect fit line
min_val = min(y_physical.min(), y_pred_phys.min())
max_val = max(y_physical.max(), y_pred_phys.max())
plt.plot([min_val, max_val], [min_val, max_val], 'r--', lw=2, label='Perfect Prediction')


plt.xlabel('Actual Strength', fontsize=16, fontweight='bold')
plt.ylabel('Predicted Strength', fontsize=16, fontweight='bold')
plt.legend(fontsize=14)
plt.grid(False)
plt.tick_params(axis='both', which='major', labelsize=14, length=6, width=2)

plt.show()

# Extract importances
importances = model.feature_importances_
feature_names = X
indices = np.argsort(importances)[::-1] # Sort descending

plt.figure(figsize=(10, 6))
plt.barh(np.array(feature_names)[indices], importances[indices], color='green', label='Feature Importance')
plt.xlabel('Feature', fontsize=16, fontweight='bold')
plt.ylabel('Feature', fontsize=16, fontweight='bold')
plt.legend(fontsize=14)
plt.grid(False)
plt.tick_params(axis='both', which='major', labelsize=14, length=6, width=2)
plt.gca().invert_yaxis()
plt.show()

target_strength = 40.0
strength_tolerance = 2.0  # Search for 38 - 42 MPa
n_search_samples = 50000

search_space = pd.DataFrame()

for col in X:
    min_val = df[col].min()
    max_val = df[col].max()
    search_space[col] = np.random.uniform(min_val, max_val, n_search_samples)

predicted_strengths = model.predict(search_space)

if len(valid_indices) > 0:
    valid_mixes = search_space.iloc[valid_indices].copy()
    valid_mixes['Predicted_Strength'] = predicted_strengths[valid_indices]


valid_mixes['Total_Binder'] = valid_mixes['Cement'] + valid_mixes['Slag'] + valid_mixes['FlyAsh']

best_mix = valid_mixes.loc[valid_mixes['Total_Binder'].idxmin()]

print(f"\nOptimized Mix for Target {target_strength} MPa (Least Binder Content):")
print("-" * 50)
print(f"Predicted Strength: {best_mix['Predicted_Strength']:.2f} MPa")
print(f"Total Binder:       {best_mix['Total_Binder']:.2f} kg/m^3")
print(f"Cement:             {best_mix['Cement']:.2f} kg/m^3")
print(f"Slag:               {best_mix['Slag']:.2f} kg/m^3")
print(f"FlyAsh:             {best_mix['FlyAsh']:.2f} kg/m^3")

